name: Update Velog

on:
    push:
        branches:
            - main
    schedule:
        - cron: '0 0 * * *'
    workflow_dispatch: # 수동 실행을 위한 이벤트 추가

jobs:
    update_velog:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
       
            - name: Configure Git
              run: |
                  git config user.name 'NuyHesHUB'
                  git config user.email 'shjoo@intube.kr'
        
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
        
            - name: Install dependencies
              run: |
                  pip install feedparser gitpython

            - name: Run script
              run: python scripts/update_velog.py

            - name: Pull and Push changes
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_PAT_VELOG }}
              run: |
                  git pull origin main
                  git push https://x-access-token:${GITHUB_TOKEN}@github.com/NuyHesHUB/velog.git